- name: Install Git, Docker, and Docker Compose
  hosts: public # Admin
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest

    - name: Install Git + Python
      package:
        name: 
          - git
          - python3-pip
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'

    - name: Test Docker Compose
      command: docker-compose --version
